import { Chain } from "viem";
import {
  arbitrum,
  arbitrumSepolia,
  base,
  celo,
  celoAlfajores,
  sepolia,
  localhost as devChain1,
  lukso,
  luksoTestnet,
  mainnet,
  optimism,
  polygon,
  polygonMumbai,
  optimismSepolia,
  avalanche,
  fantom,
  scroll,
  seiDevnet,
  avalancheFuji,
  fantomTestnet,
  zkSync,
  zkSyncSepoliaTestnet,
} from "viem/chains";

export const supportedChains: Chain[] = [
  arbitrum,
  arbitrumSepolia,
  base,
  celo,
  celoAlfajores,
  sepolia,
  devChain1,
  lukso,
  luksoTestnet,
  mainnet,
  optimism,
  polygon,
  polygonMumbai,
  optimismSepolia,
  avalanche,
  fantom,
  scroll,
  seiDevnet,
  avalancheFuji,
  fantomTestnet,
  zkSync,
  zkSyncSepoliaTestnet,
];
